name: CI

on:
  pull_request_target

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DEMO_SECRET: ${{ secrets.DEMO_SECRET }}
    steps:
      - name: Checkout PR code (VULNERABLE)
        uses: actions/checkout@v4
        with:
          allow-unsafe-pr-checkout: true
      - name: Build
        run: bash build.sh
